branches: "master"
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
bundler_args: "--without development"
language: "ruby"

rvm:
- 1.9.3
- 2.0.0
- 2.1.5

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.2"
    - PUPPET_GEM_VERSION="~> 3.7"
    - PUPPET_GEM_VERSION="~> 3.8"


# glitter + github integration
#- https://webhooks.gitter.im/e/4b40092cfdac1cef4538
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7b66c720cb43789e9b80
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
